[versions]
java = "21"
kotlin = "2.2.10"
paper = "1.21.8-R0.1-SNAPSHOT"
run-paper = "2.3.1"
userdev = "2.0.0-beta.18"
shadow = "9.0.2"

[plugins]
kotlin-plugin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "userdev" }